anuraghazra/github-readme-stats

api/index.js, api/pin.js, package.json, readme.md, src/renderRepoCard.js, src/renderStatsCard.js, src/utils.js, tests/renderRepoCard.test.js, tests/renderStatsCard.test.js
It would be nice if users could pass some colors to customize their stats. So I implemented the following structure:
```md
```
The result will be something like this:
=> feat: receives text, title and icon colors from URL

src/fetchStats.js
Total stars count was missing lot of repos because github's limitation to fetch 100max repos but i solved it by sorting the repos by `STARGAZER` count
=> fix: fixed total stars count stat

src/getStyles.js, src/renderStatsCard.js, tests/renderStatsCard.test.js
Woho! now this is an amazing feature to have! :tada:
=> feat: added animations!

api/index.js, api/pin.js
I tried adding a cache (1h, but can be changed) to help with the commit count problem. It reduced Anshuman Verma's request from 4.5s avg to 185s avg in subsequent requests. The first request took a bit longer. 
This approach has a problem, though. The stats will only refresh once the cache max-age has expired, I guess it's not that big of a deal, shield.io and similar tend to have cache in place.
=> Add cache to function response

api/index.js, api/pin.js, src/fetchRepo.js, src/fetchStats.js, src/retryer.js, src/utils.js, tests/fetchStats.test.js, tests/retryer.test.js
Work in Progress, special thanks to @filiptronicek @ApurvShah007 @garvit-joshi
fixes #51 
TODO:
- write tests
- refactor code
- add retry logic in pin.js
=> fix: increase github rate limit with multiple PATs

readme.md
Corrected many instances of "Github" to "GitHub", fixed the punctuation on some sections, fixed the ~lack of~ uppercase chars in others, tweaked the grammar a bit, and added the Vercel guide to a spoiler-ish section so it's only visible if you click to expand.
<3
=> Fixed typos, punctuation [...]

src/calculateRank.js, src/fetchStats.js, src/renderStatsCard.js, tests/calculateRank.test.js
NOTE: i suck at math, so i'm just experimenting and doing trial and error to get the correct results.
=> improve: improved rating algorithm wip

src/fetchRepo.js, tests/fetchRepo.test.js
filtering out private repos just in case, otherwise if a user somehow found out the name of any of the PAT owner's private 
*(assuming they created the PAT with private repo access)* repos's name then the user could see the repo in github extra pins.
=> fix: filter out private repos

readme.md
I was a little confused at first setting the bg_color, since it said `hex color` but had `rgba(...)` so I copied the title color which of course didn't work since it started with `#` I think this makes it a bit clearer how to use it!
=> Changed hex colors to be copy/paste workable

src/renderStatsCard.js
Close #59 
Close #85
**This is consider as a workaround.**
Since `transform: scale()` on the SVG text-tag is still having issue on WebKit.
=> fix: fixed CSS scale() issue on WebKit by wrap up text in g tag

src/getStyles.js
issue #104 
add css font config `Helvetica Neue` to `.stat`.
Fix style collapse in Japanese MacOS.
=> fix style collapses on stats card by css font config

src/renderStatsCard.js, tests/renderStatsCard.test.js
this PR focuses on two things:
- if the user's name ends with an `s`, no longer add `'s` at the end
- fix an issue where `GITHUB_TOKEN` from the env variables would no longer be respected, instead attempting to use ``process.env[`PAT_${retries + 1}`]`` &mdash; #58
=> Added proper apostrophe in stats card's header

readme.md
People may get confused when skimming over the setup process and use GITHUB_TOKEN as the PAT name. Modified the image so that PAT_1 shows as the token name instead of GITHUB_TOKEN.
Motivation: #111
=> clarify import project PAT name

themes/README.md
Added prussian theme to themes preview. https://github.com/anuraghazra/github-readme-stats/pull/123
PD: As the cache is 86400 it will take some time until it is updated, I can't think of any good solution at the moment. Apart from making it 0 and then update it to 86400 again.
=> Added "prussian" theme to themes/README preview

api/index.js, api/top-langs.js, readme.md, src/renderTopLanguages.js, src/utils.js, tests/renderTopLanguages.test.js
=> Hide specific languages in "Top languages" card

api/index.js, api/top-langs.js, codecov.yml, readme.md, src/utils.js, tests/api.test.js, tests/renderStatsCard.test.js
=> fix: hide parameter array implementation

readme.md
=> docs: fix typo in top lang section

src/renderStatsCard.js, tests/renderStatsCard.test.js
Currently when you hide the border on the stats card, you're also removing the background color, therefore breaking the theme.
Production: https://github-readme-stats.vercel.app/api/?username=terror&hide_border=true&theme=dark
This PR fixes this bug.
My Deployment: https://github-readme-stats-fc6mcm9vh.vercel.app/api/?username=terror&hide_border=true&theme=dark
=> fix: stats hide border bug

api/index.js, readme.md, src/fetchStats.js, tests/api.test.js, tests/fetchStats.test.js
Hello, this PR should fix #139 
I would like your opinion about my approach to add the `count_private` flag to the fetcher, the reason why i decided to do it this way, is because it might impact the rank quite a bit so it should add the private count to the `totalContributions` on the fetch.
If you would rather me do it differently please let me know.
Also, I know that the issue only mentions the totalcontributions but I believe we could add the number of private repos to the totals as well? If that is the case are you interested in me adding it?
=> Add private contributors to totalContributions

readme.md, readme_cn.md, src/renderTopLanguages.js, tests/renderTopLanguages.test.js, themes/index.js
Please check if your PR fulfills the following requirements:
Compact layout for top languages card similar to GitHub's lang card.
#134
=> compact layout for top languages card #134

src/fetchTopLanguages.js
- Fetch top language in each repo by adding `orderBy: {field: SIZE, direction: DESC}` constrain.
- Using the most recent 100 repositories for calculation.
=> fix: fetch top lang in each repository

src/fetchTopLanguages.js, src/renderTopLanguages.js, tests/renderTopLanguages.test.js, tests/top-langs.test.js
This Fix improves the top languages card's stats by instead of counting only the first language returned from repos it counts all the languages in a repo. 
fixes #136 
Also checkout my this comment https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665172181
=> feat: improved top lang fetching & changed title

readme.md
Add extra reminder for folks who trying to hide languages with uri-reserved characters like "c++" or "jupyter notebook".
Demo:
```
[![swapnanildutta](https://github-readme-stats.vercel.app/api/top-langs/?username=swapnanildutta&hide=c%2B%2B)](https://github.com/swapnanildutta)
```
[![swapnanildutta](https://github-readme-stats.vercel.app/api/top-langs/?username=swapnanildutta&hide=c%2B%2B)](https://github.com/swapnanildutta)
#251
=> docs: add documentation note for uri-encoded names

CONTRIBUTING.md, readme.md, readme_cn.md, readme_de.md, readme_es.md, readme_ja.md
The following typo has been corrected.
1. Corrected instance of "Github readme stats" to "GitHub Readme Stats"
2. Corrected many instances of "Github" to "GitHub"
3. Corrected the default value of an number type was a string type. (e.g. '1800')
4. Unified to 'default', because "default" and 'default' were mixed up.
Thanks for the useful service.
My README is now cool too.
<3
=> docs: fix typo

api/top-langs.js, readme.md, src/Card.js, src/getStyles.js, src/renderRepoCard.js, src/renderStatsCard.js, src/renderTopLanguages.js, tests/card.test.js, tests/renderStatsCard.test.js, tests/renderTopLanguages.test.js
With our current approach we have to handle hide_title, hide_border and auto height adjustment logics with each card and this is causing lot of duplication in code & tests too, thats why i've created a Card.js Class to abstract away the common rendering logic. 
The Card class would automatically handle the hide title, hide border logic as well has when hiding the title it will auto adjust the content & card's height accordingly.
=> refactor: added reusable Card class to reduce code & test duplication

themes/index.js
Hi! @anuraghazra 
`Solarized` is one of the most popular color theme on text editor and terminal.
So I created themes based on solarized-dark and solarized-light.
=> Add `solarized` themes

themes/index.js
Hi! I love this colorscheme and I use on my entire system. so I would like to add this theme.
You can see preview [here](https://github.com/btwiusegentoo)
links about this colorscheme
https://www.material-theme.com/docs/reference/color-palette/
https://github.com/drewtempelmeyer/palenight.vim
https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme
Edit: Add actual pictures as preview
=> Add material-palenight theme

docs/readme_cn.md, docs/readme_de.md, docs/readme_es.md, docs/readme_ja.md, docs/readme_kr.md, docs/readme_pt-BR.md
This project is great, it makes my readme cool!😎
I noticed that all non-English readme files have been moved to `/docs` two days ago via this [commit](https://github.com/anuraghazra/github-readme-stats/commit/5a136eccdf0af839ee14253234327d82d1512f50).
Some links in these readme files are incorrect and I checked all related readme files and corrected those incorrect links.
btw, I also found that someone has already submitted a PR(#361), but he just modified `/docs/readme_kr.md` file.
I'm very happy to make a small contribution to this project.:smile:
=> correct all links in the translated readme

.gitignore, api/top-langs.js, readme.md, src/cards/top-languages-card.js, src/fetchers/top-languages-fetcher.js, tests/fetchTopLanguages.test.js
Simply allows a user to specify how many languages to show on the top-langs card, between 1 and 10. Default is still 5.
Example here: [https://benjamins-readme-stats-bt29bovd9.vercel.app/api/top-langs/?username=scitronboy&layout=compact&theme=gruvbox&num_langs=10](https://benjamins-readme-stats-bt29bovd9.vercel.app/api/top-langs/?username=scitronboy&layout=compact&theme=gruvbox&num_langs=10)
Let me know if I need to add anything else to the PR.
=> feat: number of languages param for top langs card

src/fetchers/stats-fetcher.js, tests/fetchStats.test.js
The `totalCommitsFetcher` already sends the total number of commits, we don't need to add the values returned by the GraphQL API
Fixes #298
=> Fix commits count when include_all_commits is true

src/fetchers/top-languages-fetcher.js
This is a lazy fix: the sorting now is done properly, not relying on **Object.keys** method.
Should fix #432, fix #403, and fix #303.
=> Top Languages: fix fetching

src/cards/wakatime-card.js, tests/renderWakatimeCard.test.js
The WakaTIme stats card used different casing for the title than other cards.
=> fix: use consistent case for card titles

api/top-langs.js, readme.md, src/fetchers/top-languages-fetcher.js
As requseted in https://github.com/anuraghazra/github-readme-stats/pull/480
Making different PRs for the new features
/api/top-langs/?username=USER
/api/top-langs/?username=USER&exclude_repo=REPO
Will make PRs for the other features after this one is merged, otherwise we will get merge conflicts.
=> Added "exclude_repo" option to Top Langs

api/index.js, api/pin.js, api/top-langs.js, api/wakatime.js, readme.md, src/cards/repo-card.js, src/cards/stats-card.js, src/cards/top-languages-card.js, src/cards/wakatime-card.js, src/common/I18n.js, src/common/utils.js, src/translations.js, tests/renderRepoCard.test.js, tests/renderStatsCard.test.js, tests/renderTopLanguages.test.js, tests/renderWakatimeCard.test.js
Add translations for the cards. Fixes #508.
=> Card translations

src/translations.js, tests/renderRepoCard.test.js, tests/renderStatsCard.test.js, tests/renderWakatimeCard.test.js
1. Improve translathion of Chinese
2. Change some words into English
Some words seems not good when translating into Chinese. There is a website like GitHub in China, it also keep some words in origin. So I restored them.
=> improve: improve translathion of Chinese

docs/readme_cn.md, docs/readme_de.md, docs/readme_es.md, docs/readme_fr.md, docs/readme_it.md, docs/readme_ja.md, docs/readme_kr.md, docs/readme_pt-BR.md
Unfortunately, I cannot guarantee that all of these translations are grammatically correct. But I think that it would be better if these translations would be corrected later than information about these options would be missing.
=> Added missing stats card options in docs translations

readme.md
I did not understand the ranks at first sight and did not find "A++" in the issues nor in README.md. After a more closer investigation, I saw the reference to the code. I tried to understand the code and to formulate some small explanation. The result is open sourced in this PR.
=> Add explanation of the ranks

readme.md
Some people unfamiliar with URL encoding may get confused by this, when this site can just handle it for them.
=> URL Encoding Help

docs/readme_cn.md, docs/readme_de.md, docs/readme_es.md, docs/readme_fr.md, docs/readme_it.md, docs/readme_ja.md, docs/readme_kr.md, docs/readme_nl.md, docs/readme_np.md, docs/readme_pt-BR.md, docs/readme_tr.md, readme.md
- Remove common option for all cards. `hide_border `
Currently, `hide_border` is a valid option for all cards, so there is no need to list it as a separate option.
- Updated Stats Card and Language Card options for Japanese.
( related #815 )
=> docs : Update readme parameter

readme.md
Correct typos and difficult word choices.
=> Remedy typos

src/translations.js
Wakatime is a name of the service, it cannot be translated
=> Improved russian translation of wakatime stats card

.gitignore, src/cards/wakatime-card.js, tests/__snapshots__/renderWakatimeCard.test.js.snap
This fix the rendering problem on the right end of the bargraph on wakatime compact card, as seen in the pictures below.
Before:
After:
=> fix: wakatime compact card bargraph rendering

api/index.js, api/pin.js, api/top-langs.js, api/wakatime.js, readme.md, src/cards/repo-card.js, src/cards/stats-card.js, src/cards/top-languages-card.js, src/cards/wakatime-card.js, src/common/Card.js, tests/renderRepoCard.test.js, tests/renderStatsCard.test.js, tests/renderTopLanguages.test.js, tests/renderWakatimeCard.test.js
Cards are rounded by default which looks kinda ugly when you have two adjacent cards with a dark theme and a light background.  I added support for a parameter which allows users to control the rounding used by the card (and had it default to the original 4.5).  I added implementation, tests, and readme docs but feel free to ping me if I missed anything.
=> add corner rounding parameter so we can make square cards

readme.md
=> Correct code block language in readme.md

CONTRIBUTING.md
This resolves #1012 - the `npm install` step was not in the docs and is required after cloning the repo (obv. while this is normal for node-based projects, since it was not in the steps I was assuming that e.g. the `vercel` or `vercel dev` steps would have automatically installed any required dependencies - and in any event it is I think definitely a required step.)
=> docs: add `npm install` step to CONTRIBUTING.md

api/pin.js
Fixes #1011 - Think this is fairly straight-forward and non-controversial. Also tested, and works as required with this change. Thanks. (And thanks for a great project! 😊)
=> fix: apply parseBoolean to hide_border in pin.js

api/wakatime.js, docs/readme_de.md, docs/readme_es.md, readme.md, src/cards/wakatime-card.js
This adds a parameter called `langs_count` for limiting the number of languages shown on `wakatime` cards and closes #968
=> Add langs_count option in Wakatime languages cart

src/common/Card.js
the function renderGradient returns  undefined if colors.bgColor !== "object"
which may render "undefined" into SVG
and actually, it has already done so
=> fix: return "" instead of return undefined

src/fetchers/wakatime-fetcher.js
As of right now an `api_domain` with a subfolder doesn't work. Some wakapi users that end up hosting their own server, may end up using a subfolder, instead of a subdomain, just like I did on mine.
So following doesn't work
```
api_domain=example.com/wakapi
```
because currently it becomes `api_domain=example.comwakapi`
giving the following output
I already tested this on my forked repo, so I know it works. https://github.com/AlexandroPerez/github-readme-stats
I don't know if changes will need to be made to make the provided api_domain safe, but as of now it only removes a trailing `/` at the end of the value. 
Fixes #1026
=> Add subfolder support in api_domain

CONTRIBUTING.md
Editorial:
* The previous answer made no sense, since the question is `How to count PRIVATE stats` and the answer was `We can only count private commits`.
* Grammar
=> Editorial: Grammar & content error

src/cards/stats-card.js, src/translations.js
Changes the wording "Total Stars" to "Total Stars Earned" for less confusion. 
TODO
=> feat(stats): change total stars to total stars earned

readme.md
'?theme' does not work, the correct option to use is '&theme'.
=> Replace '?theme' with '&theme'

src/cards/repo-card.js, src/cards/top-languages-card.js, src/common/utils.js, tests/flexLayout.test.js, tests/renderRepoCard.test.js, tests/utils.test.js
=> feat(layout): improve flexLayout & fixed layout overlaps

api/wakatime.js
- closes #1362 
- This PR fixes the bug shown in this issue: #1362 
- There was a simple error when importing the function `isLocaleAvailable`, and it was fixed by changing the file from which the function is imported.
=> Fix wakatime card translations server error

src/cards/wakatime-card.js, tests/renderWakatimeCard.test.js
Fixes: #1396 
For some reason the wakatime API returns "undefined" for languages in this particular case. This change prevents error in that case and normal "No coding activity this week" message is shown. Also added a test case to validate this.
The particular example case also has hide_title=true and layout=compact, so the card will be just empty. Without those it will be like this:
=> Fixed bug where wakatime api returns undefined languages

themes/index.js
Added [Aura Theme](https://github.com/daltonmenezes/aura-theme), also Aura has [theme for VSCode](https://marketplace.visualstudio.com/items?itemName=DaltonMenezes.aura-theme)
=> feat(themes): aura theme

tests/fetchTopLanguages.test.js
This pull request adds a test for the `exclude_repo` option to the language card tests. This test was not added in d4e2a1b39582951d7c301eeec8a92a1edf33d75d.
=> test: adds language card 'exclude_repo' test

api/top-langs.js
This pull request removes the `hide` argument from the `fetchTopLanguages` call found in the `top-lang.js` file. This was done since this was leftover from 465faa7c32983bbc53080f111fa49f5a2629ecd2.
=> remove lang fetch hide arg

readme.md
Updated the Vercel PAT setup instructions.
The original instructions don't say to enable `repo` permissions on the Personal Access Token. Without these permissions, the widget was not able to count the `total commits` on my private repos. I updated the instructions to specifically mention enabling the `repo` permission on the PAT.
I tested this using my own Vercel instance and can confirm the `repo` permission is needed.
This fix has been mentioned here: https://github.com/anuraghazra/github-readme-stats/issues/1275#issuecomment-929887319
=> Fixed Vercel PAT setup instructions

src/translations.js
Add traditional Chinese (zh-tw)
=> Add traditional Chinese (zh-tw)

api/pin.js, src/cards/repo-card.js, src/cards/stats-card.js, src/cards/top-languages-card.js, src/cards/types.d.ts, src/cards/wakatime-card.js, src/common/utils.js, src/fetchers/repo-fetcher.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js, src/fetchers/types.d.ts, src/fetchers/wakatime-fetcher.js, src/getStyles.js
- TODO: Refactor types
- TODO: Organize types
=> refactor(cards): added typings for cards and fetchers

src/common/utils.js, src/fetchers/repo-fetcher.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js, src/fetchers/wakatime-fetcher.js, tests/fetchWakatime.test.js
=> feat: added better error messages

themes/index.js
This is #892 rebased on the current master branch.
=> rose pine/master rebase

src/cards/stats-card.js
It seems that the rank text of "GitHub Stats Card" is not centering.
```js
const circle = document.querySelector(".rank-circle").getBoundingClientRect()
const text = document.querySelector(".rank-text").getBoundingClientRect()
console.log(circle.x + circle.width / 2, circle.y + circle.height / 2) // => 390 110.5
console.log(text.x + text.width / 2, text.y + text.height / 2)         // => 391 107.5
```
```js
// at https://github-readme-stats.vercel.app/api?username=anuraghazra
const circle = document.querySelector(".rank-circle").getBoundingClientRect()
const text = document.querySelector(".rank-text").getBoundingClientRect()
console.log(circle.x + circle.width / 2, circle.y + circle.height / 2) // => 390 110.5
console.log(text.x + text.width / 2, text.y + text.height / 2)         // => …
```
=> fix(style): centering rank text in the circle

package.json
As discussed in https://github.com/anuraghazra/github-readme-stats/discussions/712 axios should be labelled as a dependency while prettier should be labelled as a dev dependency. This Pull request solves this.
=> refactor: fix incorrect dependency types

src/common/Card.js
Hi all,
I'm building an UI generator for stats cards recently, and I noticed that `bg_color` with gradient result is unexpected in most rotate angles, I think the point is `gradientUnits` attribute, so issue this PR for set it to `userSpaceOnUse` if its ok.
=> feat: gradient units to userSpaceOnUse

docs/readme_cn.md, docs/readme_de.md, docs/readme_es.md, docs/readme_fr.md, docs/readme_it.md, docs/readme_ja.md, docs/readme_kr.md, docs/readme_nl.md, docs/readme_np.md, docs/readme_pt-BR.md, docs/readme_tr.md
The same changes as in merged pull request #949 but in the whole project.
=> docs(translations): corrected code blocks language

src/common/utils.js
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace the git.io link with its actual URL.
=> chore: replace `git.io` links

docs/readme_de.md, docs/readme_es.md, docs/readme_fr.md, readme.md
I linked the possible values of the `hide` URL param to the description of the aforementioned param and translated my changes to the different translations of the README in the languages known to me.
=> 📝 Linked "hide" URL param values to its description

readme.md
This commit adds a link to the discussion page to make sure people ask questions there instead of opening issues.
=> docs: add discussion button to readme

src/translations.js
I checked in Safari, Chrome, Firefox it was all same, "Contribute" 's , Japanese translation was too long to so text was overlap the numbers. its fixed by changing shorter word.
=> japanese translation fix

readme.md
Add a small note to make users aware that the wakatime card currently only works with public profiles.
=> docs: add wakatime public profile note

.github/workflows/test.yml
This commit fixes an npm dependency error that caused the test action to fail.
=> fix: prevent npm dependency error

package.json
This PR pins the node version to >=13 since node 12 is now end of life (see https://vercel.com/changelog/node-js-12-is-being-deprecated).
=> build: pin node version to >=13 (#1900)

src/calculateRank.js, src/fetchers/stats-fetcher.js
On new/empty GitHub profiles, the card would previously appear like this with `include_all_commits` enabled...
```
https://github-readme-stats.vercel.app/api?username=USERNAME&include_all_commits=true
```
And now it has the same behaviour as without `include_all_commits`...
=> Fix NaN and undefined for empty profiles

.github/workflows/test.yml, package.json, scripts/generate-langs-json.js, src/calculateRank.js, src/cards/repo-card.js, src/fetchers/wakatime-fetcher.js, tests/fetchTopLanguages.test.js, tests/fetchWakatime.test.js, tests/renderWakatimeCard.test.js, themes/index.js
Fixes https://github.com/anuraghazra/github-readme-stats/issues/1899
Theme preview action is not working because diff includes a change in the previous line, where we added a comma. And when you run `Hjson.parse()` in preview-theme.js, it couldn't recognize the added diff as a valid json.
Ensure a trailing comma is always added in `themes/index.js`, to prevent unnecessary line diff. To do that, I saw that we already have a [prettier config](https://github.com/anuraghazra/github-readme-stats/blob/8aea1e3c353e3cf1d3704d5ce7f4b52888ddbc97/.prettierrc.json), so I make sure the CI runs that to enforce the rule (following this [guide](https://lietzau-consulting.de/2022/03/integrate-prettier-circle-ci/))
This PR is divided into 2 commits. The first adds prettier to the CI. The second are changes …
=> Add prettier check to CI

.github/workflows/empty-issues-closer.yaml
This PR adds a simple GitHub action that automatically closes empty issues.
=> ci: add empty issues closer action

.github/workflows/generate-theme-doc.yml, .github/workflows/test.yml, .gitignore, package-lock.json
Use `npm ci` nstead of `npm install` in actions (see https://docs.npmjs.com/cli/v8/commands/npm-ci).
=> ci: switch to npm ci in github actions

package-lock.json, package.json, src/cards/wakatime-card.js
This PR adds a workaround for importing the `languageColors` JSON file. This needed to be done since Vercel uses v16.4, which does not support JSON file importing without the `experimental-json-modules` flag. See https://simonplend.com/import-json-in-es-modules/ for more information. The workaround can be found [here](https://stackoverflow.com/questions/66726365/how-should-i-import-json-in-node).
=> build: fix wakatime json import bug

.github/workflows/preview-theme.yml, scripts/preview-theme.js
This commit makes sure that:
- The theme-preview action can test multiple themes.
- Fails if something goes wrong.
- Requests changes if the theme does not adhere to the guidelines.
- Approves the PR if the theme adheres to the guidelines.
@anuraghazra I think this behaviour is more friendly than #2060. You can see it in action on https://github.com/rickstaa/github-readme-stats/pull/15. I will add the tests below so that you can review them. After that, I will create an action that closes theme PR, which stays unchanged for several days.
=> ci: improve theme-preview action

scripts/preview-theme.js
This commit makes sure that 4,5,6,8 digit hex colours are also accepted. It further also includes the border_color attribute in the tests.
=> ci: improve theme preview action

.github/workflows/e2e-test.yml, .github/workflows/generate-theme-doc.yml, .github/workflows/preview-theme.yml, .github/workflows/test.yml
I updated workflows to apply **dependency caching**.
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.
Node.js projects can run faster on GitHub Actions by enabling dependency caching on the [setup-node](https://github.com/actions/setup-node) action. 
The following example enables caching for a Node.js project with npm:
```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
with:
node-version: "16.x"
cache: npm
```
> It’s literally a one line change to pass the `cache: npm` input parameter. …
=> Caching Dependencies to speed up workflows

.github/workflows/e2e-test.yml, .github/workflows/empty-issues-closer.yaml, .github/workflows/generate-theme-doc.yml, .github/workflows/preview-theme.yml, .github/workflows/stale-theme-pr-closer.yaml, .github/workflows/test.yml, package.json, scripts/close-stale-theme-prs.js, scripts/helpers.js, scripts/preview-theme.js
This PR adds the `stale-theme-pr-closer` closer action. This action is used to close theme pull requests with an `invalid` label that has been stale for a given number of `STALE_DAYS`. This PR is meant to be merged in combination with https://github.com/anuraghazra/github-readme-stats/pull/2065.
=> ci: add stale theme pull request closer action push

scripts/helpers.js, scripts/preview-theme.js
This pull request fixes some small bugs that were present in the theme-preview github action script.
=> ci: fix small bugs in theme-preview action

src/calculateRank.js, src/cards/stats-card.js, src/common/retryer.js, src/common/utils.js
Added and updated docstrings to functions.
Improve function docstrings #2032
=> fix: adding docstrings to the files where it was missing

src/common/utils.js
Fixes #1774
The size of the box should be 550px to allow 25px padding from both sides. I found the width of the text using `getComputedTextLength()` method
=> Fix card length during error

src/fetchers/stats-fetcher.js, tests/api.test.js, tests/fetchStats.test.js
This fixed https://github.com/anuraghazra/github-readme-stats/issues/1177 only for the stats card part
=> fix: fetch all repos for for the stats card

tests/e2e/e2e.test.js
This PR makes sure that the cache is bursted when the e2e tests are performed.
=> test: burst cache in e2e tests

api/index.js, api/pin.js, api/top-langs.js, api/wakatime.js
This PR makes sure that errors are not cached. Doing this will prevent people from seeing the `max_retries` error longer than is needed.
=> fix: prevent errors from being cached

src/cards/stats-card.js
Text is overlapping when locale is zh-tw.
**Before**
**After**
Add `zh-tw` into `longLocales` array
=> fix: text overlapped on zh-tw locale

api/index.js, api/pin.js, api/top-langs.js, api/wakatime.js, tests/api.test.js
This commit ensures that the cache is not cached when the GraphQL limit is hit in all browsers (see https://stackoverflow.com/a/2068407/8135687 and https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-1282630614).
=> fix: improve error caching behavoir

docs/readme_kr.md, docs/readme_np.md, docs/readme_tr.md, readme.md, scripts/helpers.js, scripts/preview-theme.js, scripts/push-theme-readme.sh, src/fetchers/repo-fetcher.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js, src/translations.js
Just a quick commit to fix the capitalization of "GitHub" throughout the repo (mostly docs and comments).
=> Fix GitHub capitalization

readme.md
=> Document auto theme change #2074

src/cards/wakatime-card.js, tests/__snapshots__/renderWakatimeCard.test.js.snap, tests/renderWakatimeCard.test.js
=> Fix truncation of compact wakatime progress bar when langs_count is set

src/calculateRank.js, tests/calculateRank.test.js, tests/e2e/e2e.test.js
I think I found a missing term in the calculation of `TOTAL_VALUES` used as input standard deviation for the CDF in calculateRank.
=> Missing term in calculation of TOTAL_VALUES.

src/calculateRank.js, src/common/utils.js, src/fetchers/repo-fetcher.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js, src/translations.js
This PR migrates regular javascript functions to arrow functions.
=> refactor: migrate to using arrow functions

api/index.js, api/top-langs.js, api/wakatime.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js
This Pull request removes all occurrences of the dotenv package in the `src` folder. As explained in the Vercel documentation vercel ignores dot files (see https://github.com/vercel/vercel/discussions/3962#discussioncomment-4277). It instead loads the env variables defined in the Vercel instance. As a result, we can therefore remove dotenv. I tried to use a `.env` file, and it broke the app since then the vercel env variables won't be loaded anymore. Dotenv is now only used in the `scripts` folder.
=> refactor: remove unused dotenv calls

src/common/retryer.js
This commit makes sure that the retry function tests all PATs. Will help fix #1471.
=> fix: fix retry max-out bug

src/common/utils.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js
This commit adds an INCLUDE_ORGS ENV variable that can be used to include results from organizations into the GRS cards for self-deployed Vercel instances. 
> **Warning**
> This is a hidden feature since we can not officially support this on the Public Vercel instance due to GraphQL and Vercel rate/timeout limits. You can set this env variable via Vercel's ENV variable menu (see https://vercel.com/docs/concepts/projects/environment-variables).
=> feat: add INCLUDE_ORGS env variable

src/common/utils.js, src/fetchers/stats-fetcher.js, src/fetchers/top-languages-fetcher.js
Reverts anuraghazra/github-readme-stats#2275
=> Revert "feat: add INCLUDE_ORGS env variable"

src/cards/stats-card.js, tests/renderStatsCard.test.js
This commit prevents confusion about the Contributed to stat. Currently, only the last year's results are shown, but it looks like it is the all-time contribution count (see #2269). This commit adds a ' (last year)' suffix to prevent this confusion from happening.
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```
[![Anurag's GitHub stats](https://github-readme-stats-git-fixrepo-7dd470-github-readme-stats-team.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```md
[![Anurag's GitHub …
```
=> fix: fix repoContrib confusion (#2269)

src/cards/stats-card.js
This PR makes sure the inner card margin when `include_all_commits` is enabled is still correct now that #2274 was merged.
=> feat: fix 'include_all_commits' inner card margin

api/top-langs.js, readme.md, src/cards/top-languages-card.js, src/cards/types.d.ts, src/common/createProgressNode.js
Reverts anuraghazra/github-readme-stats#2396
@RedHeadphone Now that the problems are fixed. I will reapply your changes again. Thanks again for your contribution.
=> Revert "Revert "Add loading Animation to Most used Language card""

readme.md
=> Fix readme cache_seconds minimum listed as two hours instead of four hours

readme.md, src/fetchers/stats-fetcher.js, tests/api.test.js, tests/fetchStats.test.js
This PR enables multi-page stars' support from fetching on private Vercel instances. This feature can be disabled on the public Vercel instance but can be enabled by adding the `FETCH_MULTI_PAGE_STARS=true` as an env variable.
=> feat: enable multi page star fetching for private vercel instances

.github/workflows/deploy-prep.py, .github/workflows/deploy-prep.yml, vercel.json
Changed default `maxDuration` to `10` so that users can easily fork and deploy to Vercel.
Also added a GH Actions workflow that changes `maxDuration` to `30` so that @anuraghazra can still have 30 for his deployment.
@anuraghazra after merging you have to change Vercel deployment branch from `master` to `vercel`.
=> Vercel maxDuration fix + GH Actions workflow for Vercel deployment

src/cards/stats-card.js, tests/renderStatsCard.test.js
This PR makes sure that the card width is formatted correctly. See #2452 for more information on the current incorrect behavoir.
=> fix: fixes card overflow problem #2452

.github/workflows/e2e-test.yml, .github/workflows/empty-issues-closer.yaml, .github/workflows/label-pr.yml, .github/workflows/stale-theme-pr-closer.yaml, .github/workflows/top-issues-dashboard.yml
Prevent some actions from running on forks since they are not needed. I left the theme preview/doc, test and e2e actions enabled, as they might be people in development. We can also disable the e2e action if you think it is unnecessary (see https://github.com/anuraghazra/github-readme-stats/issues/2465).
=> ci: prevent certain actions from running on forks

.github/labeler.yml
Auto labels PRs as `documentation` if they change `readme.md`. Might also label bigger PRs where new features are added, but would be useful to keep track of which PRs change the documentation. @rickstaa what do you think?
=> Add auto-labelling for documentation updates

.github/workflows/generate-theme-doc.yml
This PR fixes a bug introduced due to a upstream change in the git package. See https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git/71904131#71904131 for more information.
=> ci: fix unsafe directory bug

src/cards/wakatime-card.js, tests/__snapshots__/renderWakatimeCard.test.js.snap
This PR fixes https://github.com/anuraghazra/github-readme-stats/issues/2434. The codebase could be cleaned up by moving the animation code into the `getStyles` function but I currently do not have the time to look at this. @Zo-Bro-23 feel free to improve this PR.
=> Fix wakatime progress bars - #2434

src/cards/top-languages-card.js, tests/renderTopLanguages.test.js
Updated the code and respective test case as well. And also fixed for minimum width difference as well. Here is the preview
=> fix: for issue #2534

scripts/preview-theme.js
Fixes the theme-preview GitHub action.
=> fix theme preview

scripts/preview-theme.js
Preview theme workflow fails. Hopefully fixes it.
=> Preview theme workflow fix

api/status/pat-info.js, api/status/up.js
This fixes some code comments and decreases the up rate limit period.
=> refactor: fix some code comments and decrease up rate limit

scripts/preview-theme.js
@Zo-Bro-23 I thought the previous pull request was the last one, but there was another error in there 😅.
=> ci: fixes theme preview action

themes/index.js
3 additional themes sticking primarily to flat colors, which the exception of icons and border being slightly darker. All 3 themes also have transparent backgrounds that will show differently per-user via GiHub's own light and dark themes. Transparency should also still provide easy readability for both. Previews are below for both of GitHub's light and dark modes.
=> Added "Shadow" set (Red, Green, Blue, transparent BG)

themes/README.md, themes/index.js
=> add github_dark_dimmed theme

src/fetchers/stats-fetcher.js
"Something went while trying to retrieve the stats data using the GraphQL API." -> "Something went wrong while trying to retrieve the stats data using the GraphQL API."
=> Updated the custom error there was a Typo.

src/cards/wakatime-card.js
Currently compact layout of wakatime card is completely empty when there are no coding activity. 
This is how it will look like
Preview deployed there: https://github-readme-stats-arc8tv92a-qwerty541.vercel.app
=> Show no activity error in compact layout of wakatime card

tests/api.test.js, tests/fetchStats.test.js
```
The previous mock logic was too simplistic and has been fixed in the
commit. If the mock logic had been properly implemented, then the
mistaken pageInfo.endCursor keys should have made the test case "should
fetch two pages of stars if 'FETCH_MULTI_PAGE_STARS' env variable is set
to `true`" stuck.
```
See also https://github.com/anuraghazra/github-readme-stats/pull/1691#issuecomment-1527401508
=> test: fix mistaken pageInfo.endCursor keys

readme.md
The old example user doesn't have a WakaTime account anymore.
=> docs: update wakatime user

readme.md, src/cards/top-languages-card.js, src/cards/types.d.ts, tests/renderTopLanguages.test.js
Preview deployed there: https://github-readme-stats-lhjkv63gq-qwerty541.vercel.app
Option: `https://github-readme-stats-lhjkv63gq-qwerty541.vercel.app/api/top-langs?username=qwerty541&layout=pie`
TODOS:
=> Top languages card pie layout

readme.md, src/cards/top-languages-card.js, src/cards/types.d.ts, tests/renderTopLanguages.test.js
Preview deployed there: https://github-readme-stats-1svgrsiyn-qwerty541.vercel.app
Option: `https://github-readme-stats-1svgrsiyn-qwerty541.vercel.app/api/top-langs?username=qwerty541&layout=donut-vertical`
TODOS:
=> Top languages card donut vertical layout

api/wakatime.js, readme.md, src/cards/wakatime-card.js, src/common/utils.js, src/fetchers/wakatime-fetcher.js, src/translations.js, tests/__snapshots__/renderWakatimeCard.test.js.snap, tests/e2e/e2e.test.js, tests/fetchWakatime.test.js, tests/renderWakatimeCard.test.js
This commit makes sure that the WakaTime card works with the new WakaTime API. See https://github.com/anuraghazra/github-readme-stats/issues/2698 for more information.
>  **Note**
> Will be merged when I have one review of somebody that does use the WakaTime card.
=> fix: Make WakaTime card compatible with new API

.github/workflows/top-issues-dashboard.yml
This pull requests will enable the top themes feature of the https://github.com/rickstaa/top-issues-action that was released in https://github.com/rickstaa/top-issues-action/releases/tag/v1.3.0. It also enables top issues labelling.
=> ci: add top themes and labels to 'top issues dashboard' action

src/cards/top-languages-card.js, tests/renderTopLanguages.test.js
Specifying `hide_progress` parameter switch card layout to compact. Currently if you use `&layout=compact` it shows 6 languages by default, but if you specify `&hide_progress=true` it still shows 5. This pull request fix this behavior.
=> Use compact layout default langs count when hide_progress param was set

CONTRIBUTING.md
I think we no longer need this note since we have automated theme preview workflow.
=> Remove redundant ask for theme screenshot from CONTRIBUTING.md

readme.md
I think we can remove this warning section since that value in  `.json` has been changed to 10 by default nowadays?
Also removed related section in self deployment guide.
=> Update readme.md about maxDuration

.github/workflows/top-issues-dashboard.yml
@qwerty541 after your recent documentation update, I noticed that the themes were not showing up in the https://github.com/anuraghazra/github-readme-stats/issues/1935 dashboard. This PR fixes this.
=> ci: fix top-issues action

readme.md
This pull request changes the README so that users are aware that they also need to set the `user` permission when creating the PAT when they want their private commits to show up.
=> docs: add  PAT permission to docs

.gitignore, .vscode/settings.json
I think it's better to keep this settings inside repository configs instead of some pull request comment. I also added there `editor.formatOnSave` config which i found very useful for myself.
=> Add vscode settings for yzhang.markdown-all-in-one extension

readme.md, src/calculateRank.js, src/cards/stats-card.js, src/fetchers/stats-fetcher.js, src/fetchers/types.d.ts, tests/calculateRank.test.js
This PR removes the S+ rank (to comply with the Japanese grading system) and adds finer ranking levels (now S, A+, A, A-, B+, B, B-, C+ and C).
I also used a different cumulative distribution function (CDF) for stars and followers. The distributions of these two stats have heavier tails (meaning that large values are more likely) than what an [exponential distribution](https://wikipedia.org/wiki/Exponential_distribution) allows. So instead I used an approximation of the [log-normal](https://wikipedia.org/wiki/Log-normal_distribution) CDF. This makes the initial ranks (C to A) more accessible, but the final rank (S) extremely hard to reach.
I also replaced the word `score` by `percentile`.
=> Add finer ranking levels

package.json
Update node version to 18 on production deployment.
#2820 can be merged after this.
=> Specify node version inside package.json

.github/workflows/top-issues-dashboard.yml
This pull request increases the number of top items in #1935 so that we have a better overview of what is important. Seven would also be okay 👍🏻.
=> increase top list size

src/cards/stats-card.js
Hey, @rickstaa! I see that you reverted this change while merging #1404. I deliberately placed the number of reviews next to the number of pull requests, because in my opinion the card looks much prettier in this way and, in general, the arrangement of these elements side by side is more logical due to their close relationship with each other. Do not you agree?
=> Stats card: Reorder total reviews count position

src/cards/top-languages-card.js, tests/renderTopLanguages.test.js
Function arguments was reordered because optional parameter cannot be previously than non-optional.
=> Fixed docstring for trimTopLanguages function

package-lock.json, readme.md, src/cards/stats-card.js, src/cards/types.d.ts, src/common/icons.js, src/getStyles.js, tests/__snapshots__/renderWakatimeCard.test.js.snap, tests/renderStatsCard.test.js
This pull request allows users to replace the rank level with the rank progress by setting the `rank_icon` query to `progress`.
```md
```
=> feat: add 'progress' rank icon

.vscode/settings.json, readme.md, src/cards/stats-card.js, src/cards/types.d.ts, src/common/icons.js, src/getStyles.js, tests/__snapshots__/renderWakatimeCard.test.js.snap, tests/renderStatsCard.test.js
This pull request adds the `percentile` option for the `rank_icon` query variable. This option displays the rank percentile the user belongs to. See https://github.com/anuraghazra/github-readme-stats/pull/2858#issuecomment-1597529697.
```md
[![Anurag's GitHub stats](https://github-readme-stats-git-addpercentilerankicon-rickstaa.vercel.app//api?username=anuraghazra&rank_icon=percentile)](https://github.com/anuraghazra/github-readme-stats)
```
[![Anurag's GitHub stats](https://github-readme-stats-git-addpercentilerankicon-rickstaa.vercel.app//api?username=anuraghazra&rank_icon=percentile)](https://github.com/anuraghazra/github-readme-stats)
@qwerty541 let me know what you think. We can also replace the `progress` option that was merged, but maybe having both options would be nice. I'm not …
=> add percentile rank icon

tests/e2e/e2e.test.js
I noticed that in last time different e2e tests failed several time due to timeout. I think we should increase default jest 5 seconds timeout (https://jestjs.io/docs/next/api#testname-fn-timeout) to prevent this errors.
Examples of failed workflows:
https://github.com/anuraghazra/github-readme-stats/actions/runs/5344257566/jobs/9688569188
https://github.com/anuraghazra/github-readme-stats/actions/runs/5344257566/jobs/9688422630
https://github.com/anuraghazra/github-readme-stats/actions/runs/5343322235/jobs/9692637166
=> Increase e2e tests timeout secs

scripts/preview-theme.js
I'm currently working on eslint integration and i found a bug inside theme preview script. Related to https://github.com/anuraghazra/github-readme-stats/pull/2882#issuecomment-1606993478
=> CI: Fix warnings variable usage inside theme preview workflow

CONTRIBUTING.md
I think it's better to place link on file that should be edit at the end. In my opinion it should increase chance that user will read carefully another notices before getting to work.
=> Docs: reorder themes contributing guidelines

.github/workflows/empty-issues-closer.yaml, .github/workflows/generate-theme-doc.yml, .github/workflows/label-pr.yml, .github/workflows/preview-theme.yml, .github/workflows/prs-cache-clean.yml, .github/workflows/stale-theme-pr-closer.yaml, .github/workflows/top-issues-dashboard.yml, .github/workflows/update-langs.yaml
This PR fixes a bug that is present when the `read` option is used for the `id-token` permission (see https://github.com/github/docs/issues/26481).
=> fix gh id token bug 2

.eslintrc.json, .github/workflows/test.yml, .husky/pre-commit, package-lock.json, package.json, src/calculateRank.js, src/getStyles.js, tests/api.test.js, tests/calculateRank.test.js, tests/card.test.js, tests/e2e/e2e.test.js, tests/fetchRepo.test.js, tests/fetchStats.test.js, tests/fetchTopLanguages.test.js, tests/fetchWakatime.test.js, tests/flexLayout.test.js, tests/pat-info.test.js, tests/pin.test.js, tests/renderRepoCard.test.js, tests/renderStatsCard.test.js, tests/renderTopLanguages.test.js, tests/renderWakatimeCard.test.js, tests/retryer.test.js, tests/status.up.test.js, tests/top-langs.test.js, tests/utils.test.js
Related to https://github.com/anuraghazra/github-readme-stats/pull/2882#issuecomment-1606993478
=> Eslint integration

.github/workflows/test.yml, .husky/pre-commit, package.json
Small PR that changes `npm run lints` to `npm run lint`. This was done for consistency with other npm projects and the `npm run format` command.
=> build: rename lint command

src/common/utils.js
Currently we are unable to fix this error since we need to set type for second argument of `.reduce()` function like `[] as Array<Array<T>>`. Otherwise it was set `never[]` by default. Can be fixed after migration on typescript.
=> Silence vscode type error in chunkArray function

SECURITY.md
Adding basic security policy to resolve code scanning alert: https://github.com/anuraghazra/github-readme-stats/security/code-scanning/43
I used this as template: https://github.com/atomist/samples/blob/master/SECURITY.md
@rickstaa What do you think about this?
=> Docs: Add security policy

src/fetchers/top-languages-fetcher.js
@rickstaa You can merge pull request #2928 after merging this one.
=> Refactor: Top langs card: Use typedef tags inside data fetcher

.eslintrc.json
Related to https://github.com/anuraghazra/github-readme-stats/pull/2913 https://github.com/anuraghazra/github-readme-stats/pull/2920 https://github.com/anuraghazra/github-readme-stats/pull/2923 https://github.com/anuraghazra/github-readme-stats/pull/2924
=> Enable valid-jsdoc eslint rule

tests/fetchGist.test.js
If files array contains only one entry function for calculating primary language by bytes count not fully covered.
=> Tests: Improve fetch gist test to increase coverage

readme.md
add "gist card" to the sentence in the `Customization` section of the `Readme.md` to specify that this type of card can also be personalized.
=> [Readme.md] Add Gist Card in Customization section

src/fetchers/top-languages-fetcher.js, tests/fetchTopLanguages.test.js, tests/top-langs.test.js
There is two error handlers inside `fetchTopLanguages` function. Having error handler on strings 78-81 makes unreachable the next more advanced error handler on strings 84-102.
=> Top langs card: Remove unreachable code from fetcher and increase tests coverage

tests/renderStatsCard.test.js
Covers the following lines with test:
https://app.codecov.io/gh/anuraghazra/github-readme-stats/blob/master/src%2Fcards%2Fstats-card.js#L275
=> Tests: Stats card: Add hide all stats and rank icon test

readme.md
At the moment these icons are not shown anywhere in documentation.
=> Docs: Show additional stats icons

.eslintrc.json
This pull request enables `require-jsdoc` eslint rule.
https://eslint.org/docs/latest/rules/require-jsdoc
=> infra: enable require-jsdoc eslint rule

src/common/utils.js
Current jsdoc is wrong since only card background color can be an array(gradient).
=> refactor: fix card colors type and function to resolve vscode type errors

tests/fetchStats.test.js
This pull request covers with tests these lines of code:
https://app.codecov.io/gh/anuraghazra/github-readme-stats/blob/master/src%2Ffetchers%2Fstats-fetcher.js#L178
=> tests(stats card fetcher): add upstream API error test when include_all_commits true

src/common/retryer.js, src/common/utils.js, tests/retryer.test.js
Related to https://github.com/anuraghazra/github-readme-stats/issues/3226
I think that retryer error message can be improved one more time to contain information about how users can avoid these error. Current error message "Maximum retries exceeded" is useless since do not tell users anything. I hope this change will reduce count of duplicates of https://github.com/anuraghazra/github-readme-stats/issues/1471
=> refactor: use more clear retryer error message (2)

.eslintrc.json
https://eslint.org/docs/latest/rules/no-this-before-super
=> infra: enable no-this-before-super eslint rule

.eslintrc.json
https://eslint.org/docs/latest/rules/no-unneeded-ternary
=> infra: enable no-unneeded-ternary eslint rule

src/fetchers/stats-fetcher.js, tests/api.test.js
@rickstaa We can also make text "file an issue at https://tiny.one/readme-stats" optional in the next pull request if your are up to approve these changes to show it only for unexpected errors to reduce count of new issues.
https://github.com/anuraghazra/github-readme-stats/blob/master/src/common/utils.js#L44
=> refactor(stats card fetcher): improve could not fetch total commits error message

src/common/utils.js, src/fetchers/stats-fetcher.js
Related to https://github.com/anuraghazra/github-readme-stats/pull/3255#issuecomment-1730102143
=> refactor: add GitHub REST API error to CustomError class

CONTRIBUTING.md
Currently we have two sections (https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#any-contributions-you-make-will-be-under-the-mit-software-license and https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#license) about license. i think that it is enough to have only one because both tells the same.
=> docs(contributing guidelines): remove duplicate license section

readme.md
Related to https://github.com/anuraghazra/github-readme-stats/issues/3332
=> docs: add available locales section

.eslintrc.json
https://eslint.org/docs/latest/rules/no-multiple-empty-lines
=> infra: enable no-multiple-empty-lines eslint rule

src/common/utils.js, tests/api.test.js
Related to https://github.com/anuraghazra/github-readme-stats/pull/3255#issuecomment-1730102143
This pull request conflicts with https://github.com/anuraghazra/github-readme-stats/pull/3274, if current will be merged earlier, it should be merged with master branch first and vice versa.
=> feature: do not aks user's to open new issues on upstream API errors

readme.md
@qwerty541, @anuraghazra, this adds a small uptime badge to the readme. So that people know when the public instance is down. This should not increase the GraphQL usage since the response is already cached every 5 minutes on Vercel's side.
=> docs: add uptime badge

.github/workflows/update-langs.yaml
The [update-langs.yaml](https://github.com/anuraghazra/github-readme-stats/blob/master/.github/workflows/update-langs.yaml) appears to lack the necessary permissions to initiate a pull request. Detailed information can be found in the [workflow run](https://github.com/anuraghazra/github-readme-stats/actions/runs/6366521987/job/17378465600). For more information on this issue, see https://github.com/anuraghazra/github-readme-stats/issues/3351.
=> ci: fix 'update-langs' ci permissions

readme.md
This pull request improved the Vercel badge position since they have been a massive sponsor since GRS began.
=> docs: improve vercel badge position

CONTRIBUTING.md
This pull request removes some local development steps found in the contributing guide that are no longer required.
=> docs(contributing): remove outdated local dev steps

express.js
This fixes where PAT tokens aren't loaded fast enough for `retrier` to see them if using a .env file.
This is aimed for when you want to deploy this project for your self and not use vercel.
=> allow usage of .env file for PAT tokens

readme.md
I think that tabled query options is much more readable.
=> docs: improve query options appereance using tables

readme.md
Hi Team!
I fixed the description in the README as it differs from the actual code.
=> fix: default value of cache_seconds in README

tests/e2e/e2e.test.js
https://github.com/anuraghazra/github-readme-stats/actions/runs/9798174067/job/27056127887
=> tests(e2e): fix stats card data name
