- api/index.js
- readme.md
Added total commits and icons support
> feat: added icons support

- api/index.js
Minor capitalization fixes to make it look better. I'm a grammar Nazi, sorry :P
> Fixed capitalization

- api/pin.js
- readme.md
> fix: fix description edge case fixes #10

- api/pin.js
> fix: fixed overflowing layout

- readme.md
Just a little something, hope it helps :)
> Some little grammar fixes and improvements.

- api/pin.js
- readme.md
- utils.js
fixes #20 
fixes SVG rendering failing because of special characters in the description
> fix: description trimming & htmlEncode

- src/fetchStats.js
> fix: fallback to login if name not found

- src/renderStatsCard.js
> design: added a rim to circle rank's progress

- api/index.js
- src/utils.js
> fix: query param booleans

- src/renderStatsCard.js
> design: fixed rank alignment

- src/renderRepoCard.js
- src/renderStatsCard.js
- src/utils.js
> fix: fixed repo card breaking in absence of primaryLanguage

- src/utils.js
`axios` is Promise based, there is no need to wrap it into a Promise constructor again
> chore: remove redundant codes

- .github/FUNDING.yml
- readme.md
Yey! Loved the project? Your support would be valuable :D
https://www.paypal.me/anuraghazra
> chore: added funding link

- api/index.js
- readme.md
- src/renderStatsCard.js
- tests/renderStatsCard.test.js
> feat: added hide_title option

- src/fetchRepo.js
- src/renderRepoCard.js
- tests/renderRepoCard.test.js
> feat: show archive badge if repo is archive

- src/renderRepoCard.js
- src/renderStatsCard.js
- src/utils.js
- tests/renderRepoCard.test.js
- tests/renderStatsCard.test.js
- tests/utils.test.js
Added a FlexLayout function to make our life easier with auto layout flows as mentioned in here https://github.com/anuraghazra/github-readme-stats/pull/97#discussion_r456799606 to solve this issue https://github.com/anuraghazra/github-readme-stats/pull/97#discussion_r456799098
But this function as some limitations since the elements are not rendered so i can't get their calculated widths before hand and make a proper flex layout engine. but this works for now.
> refactor: added FlexLayout for flex layouts

- readme.md
Hi,
Maybe you forgot this one
I tried, it works
> docs: README.md

- readme_cn.md
add Chinese translation
This project is so great, thanks for your contribution! :bow:
> :pencil: add Chinese translation

- api/index.js
- api/pin.js
- readme.md
- src/renderRepoCard.js
- src/renderStatsCard.js
- src/utils.js
- tests/renderRepoCard.test.js
- tests/renderStatsCard.test.js
- tests/utils.test.js
- themes/index.js
> feat: added inbuilt themes

- readme_cn.md
For this pulling request, I have updated and improved existing Simplified Chinese translation of README file. Details as follows:
- Added new contents from English README file that hasn't been updated in Simplified Chinese translation of README file.
- Translated contents that were left untouched by last translation.
- Replaced a number of half-width punctuation characters with full-width punctuation characters as following language usage habits. However, characters in commands and codes have been left unchanged per convenience of copying and pasting codes.
- Replaced phrases for more precise translation based on contents.
> Update & Improvements on Existing Simplified Chinese Translation of README

- api/index.js
- api/pin.js
- src/renderRepoCard.js
- src/utils.js
- tests/api.test.js
> feat: added ability to set custom cache

- readme.md
- readme_es.md
Hello 👋.
I've just completed the translation of the README file into Spanish.
I made 2 commits. I translated everything in the first one and fixed some typos in the second one.
Here's the Spanish word into Spanish so you can add it to the original README file: `Español`.
> Spanish translation file

- readme_es.md
* Replaced "customizar" with "personalizar"
* Added link to theme preview
> Edited readme_es

- .gitignore
- themes/index.js
> Added new theme

- api/top-langs.js
- readme.md
- src/fetchTopLanguages.js
- src/renderTopLanguages.js
- tests/fetchTopLanguages.test.js
- tests/renderTopLanguages.test.js
- tests/top-langs.test.js
NEW FEATURE :tada:
Added a `/api/top-langs` route which would show user's top 5 languages.
DONE:
- Fetching logic
- Rendering logic
- Themes support
TODO: 
- Write tests
- More customization work
> feat: added Top languages card

- src/renderTopLanguages.js
> fix: fixed sorting of languages by percentage

- vercel.json
> chore: add redirect to gh repo

- .gitignore
- api/pin.js
- package.json
- src/fetchRepo.js
- src/fetchStats.js
- src/fetchTopLanguages.js
- src/renderRepoCard.js
- src/retryer.js
- src/utils.js
- tests/pin.test.js
- tests/renderRepoCard.test.js
- tests/retryer.test.js
This PR contains couple of fix, modify and others.
- **feat:** added template options
- **added:** git ignore `.vscode` and `yarn.lock`, logger utility, test case, husky hooks to test before commit
- **replace:** all console log with logger utility
- **disable:** log disable in test environment
> feat: added isTemplate badge & refactored console.logs

- src/renderRepoCard.js
- tests/renderRepoCard.test.js
> fix: languages color fallback & hide lang if not present

- readme.md
- readme_cn.md
- readme_es.md
Changed bug and feature links in readme and some styling issue (`:`). 
This will filter out issues based on label which tagged with issue.
> docs: changed bugs and feature link

- readme_cn.md
1. add `Hide individual languages`
2. remove `hide_langs_below`
> update Hide individual languages for readme_ch

- themes/index.js
> Add: Vue theme

- src/renderStatsCard.js
- src/utils.js
> fix: weird unicode char

- api/index.js
- src/utils.js
- tests/api.test.js
- tests/utils.test.js
> chore: added secondary warning message in renderError

- themes/index.js
Please check if your PR fulfills the following requirements:
Add a shade of purple theme
> 📦 ADD: shade of purple theme

- themes/index.js
Add Sarah Drasner's Night Owl Theme to GitHub Readme Stats.
> Add Night-Owl Theme

- themes/index.js
> 👌 IMPROVE: Shades of Purple Icon color

- themes/README.md
- themes/index.js
> chore(themes): add buefy configuration

- themes/index.js
I added a new theme. Hope you like it.
> adds a new theme: "blue-green"

- themes/index.js
Added this new themes that I named algolia
hope you all like it
> added: theme algolia

- scripts/generate-theme-doc.js
- themes/README.md
Fixing obvious bugs in theme docs which i completely missed. lol
> fix: readme generation script

- themes/index.js
Hi, this theme is inspired by the colors of the popular book/movie "The Great Gatsby"
Hope you like it!
> Added Gatsby Theme

- readme.md
- readme_cn.md
- readme_es.md
- readme_ja.md
add Japanese translation.
I want to contribute to this great project.
If you'd like, please use these changes to further improve this project.
> add Japanese translation

- readme.md
- readme_cn.md
- readme_de.md
- readme_es.md
- readme_ja.md
Thanks for supporting the project @ahmadawais 
<a href="https://a.paddle.com/v2/click/16413/119403?link=1227">
</a>
<a href="https://a.paddle.com/v2/click/16413/119403?link=2345">
</a>
> chore: added @ahmadawais support badges

- readme.md
> README typo tweak

- readme_es.md
I've updated the Spanish readme, it was a bit outdated.
@JoseDeFreitas, @moonantonio If you want to check it out and see if I missed something.
> Updated readme_es.md

- readme.md
Hi,
I really liked this work ❤️ .  well done on that 💪 . I  want to contribute more.
For  now I have made change this so that it is noticeable for the first time users.
> Update : Documentation :: make the the text bold

- themes/index.js
adding a www.nordtheme.com inspired theme using nord0, nord4, nord8 & nord9
> Add Nordtheme

- themes/index.js
I add gotham-theme.
What do you think this patch?
> https://github.com/whatyouhide/vim-gotham
> Add gotham theme

- readme_cn.md
Optimizied Translation, make it more native. 优化修改了一部分中文表达！
> Optimize Chinese Translation

- themes/index.js
> Add graywhite

- readme.md
- readme_kr.md
Hello ✋ 
I'm happy to contribute to a good project.
For more users including Koreans users, I translated the README file into Korean :D
> docs: Korean translation

- themes/index.js
This is one of my favorite vs code themes.
> [themes] Add vue theme of vs code

- readme.md
- src/common/Card.js
- src/common/utils.js
- tests/card.test.js
- Improved/refactored code
- Fixed tests
- Ability to use multiple color stops
- documentation
> refactor: Improved gradient

- docs/readme_de.md
👋 Hey!
I updated the German translation of the readme.md. 
It should now again contain 100% of the information found in the English version but translated into nice and crisp German.
Btw, cool project! :)
> readme: updated German translation

- readme.md
Corrected Misspelt words [Separated, Languages]
> Corrected Spellings

- themes/index.js
@anuraghazra I added the theme and this time I took a screenshot. I hope it looks cool.
> Added chartreuse-dark theme

- api/index.js
- api/pin.js
- api/top-langs.js
- src/common/blacklist.js
Temporarily blacklisting few usernames because these are causing serverless function timeouts.
> fix: added temporary blacklist

- docs/readme_ja.md
#393
kept up with the latest README
> Update Japanese translations

- docs/readme_ja.md
This PR fixes anchor links in Japanese version of readme.
> Fix links in readme_ja.md

- themes/index.js
Made with the color scheme from [ReactJS Website](https://reactjs.org/).
> Added "react" theme

- themes/index.js
Hi, I was hoping to add this theme, the "Midnight-Purple" for those who want a truly dark purple feel.
I hope you like it!
> Added Midnight-Purple Theme

- themes/index.js
Hi! this theme i love use on vscode called `Omni` and maybe you like it too.
Based by https://github.com/getomni/vscode-omni.
> Add Omni theme

- docs/readme_cn.md
fix all-available-themes link
fix theme-config-file link
> fix links in readme_cn.md

- readme.md
Correct some spelling mistakes 😉
> 📝 typo corrections

- themes/index.js
Good day. I created a 'dark-vue' theme and would like to share it with others.
> Added dark-vue theme.

- readme.md
Fixed 27 spelling and grammar issues in Readme
> Fixed spelling and grammar errors in Readme

- src/fetchers/stats-fetcher.js
> Stats Fetcher: include stars of forked repos

- api/wakatime.js
- package.json
- readme.md
- src/cards/wakatime-card.js
- src/fetchers/wakatime-fetcher.js
- tests/fetchWakatime.test.js
- tests/renderWakatimeCard.test.js
This PR allows users to create a card displaying their wakatime stats and progress. Wakatime is a tool to track developement time.
> Add wakatime card

- themes/index.js
> Indian theme added to readme-stats

- src/fetchers/stats-fetcher.js
- tests/fetchStats.test.js
> fix: wrong total commits

- docs/readme_cn.md
- docs/readme_de.md
- docs/readme_es.md
- docs/readme_fr.md
- docs/readme_it.md
- docs/readme_ja.md
- docs/readme_kr.md
- docs/readme_pt-BR.md
- readme.md
Add `hide_border` option in all language docs
> docs: add hide_border option in all language docs

- themes/index.js
This theme is based off the vscode theme, [Blueberry Dark](https://marketplace.visualstudio.com/items?itemName=peymanslh.blueberry-dark-theme)
Preview:
> Add theme "blueberry"

- src/translations.js
Added a Greek translation for widgets (locale: `el`)
> Greek translation

- themes/index.js
Added a new theme, included is a screenshot of the theme in action.
> Added new theme "kacho-ga"

- src/cards/stats-card.js
#610
https://github-readme-stats-git-patch-capital-s.nthnchu.vercel.app/
> fix: names ending in "X" or "S"

- api/index.js
- readme.md
- src/cards/stats-card.js
- src/common/Card.js
- tests/__snapshots__/renderWakatimeCard.test.js.snap
> feat: added disable_animations flag

- src/translations.js
Some _pt-br_ translations in `/src/translations.js` are wrong, in this PR I'm fixing them.
> Fix pt br translations on /src/translations.js

- src/translations.js
- tests/renderStatsCard.test.js
Localise with English annotated
Less delocalization than #539
@jalenchuh Please review
> Polish Chinese translation

- api/wakatime.js
- src/fetchers/wakatime-fetcher.js
Fixes #608
Demo (https://github-readme-stats-git-wakatime-custom-url.nathanchu.vercel.app/api/wakatime?username=nathanchu&api_domain=wakatime.com):
[![](https://github-readme-stats-git-wakatime-custom-url.nathanchu.vercel.app/api/wakatime?username=nathanchu&api_domain=wakatime.com)](https://github-readme-stats-git-wakatime-custom-url.nathanchu.vercel.app/api/wakatime?username=nathanchu&api_domain=wakatime.com)
> feat: add support for custom wakatime api domain

- readme.md
Some minor changes to readme.md.
> added some small improvements.

- docs/readme_cn.md
- docs/readme_de.md
- docs/readme_es.md
- docs/readme_fr.md
- docs/readme_it.md
- docs/readme_ja.md
- docs/readme_kr.md
- docs/readme_nl.md
- docs/readme_np.md
- docs/readme_pt-BR.md
- docs/readme_tr.md
- scripts/generate-theme-doc.js
- themes/README.md
The same changes as in merged pull request #657 but in the whole project.
> docs(translations): some minor improvements

- themes/index.js
> new vscode theme:outrun

- src/translations.js
According to https://docs.github.com/cn/github/collaborating-with-issues-and-pull-requests , change "提案" into "拉取请求".
> Improve Chinese Translation

- themes/index.js
Ocean dark theme based on Material Themes
ocean_dark:{
title_color: "24487f",
icon_color: "7F4DA8",
text_color: "9EE504",
bg_color: "24487f",
}
> Ocean Dark Theme

- themes/index.js
> Added the City Lights Theme

- docs/readme_de.md
Removed some Spelling Mistakes
> Update DE Readme

- themes/index.js
> Discord Old Blurple

- readme.md
Customization had loads of parts, so I just improved navigation for all of them.
> Made Customization navigation better.

- docs/readme_cn.md
env name should be PAT_1, but on the picture is GITHUB_TOKEN
> docs(cn): replace error picture

- themes/README.md
> docs(theme): Auto update theme readme

- themes/index.js
---
[card]: https://github-readme-stats.vercel.app/api?username=HorebParraud&count_private=true&hide=contribs,prs,issues&show_icons=true&title_color=ff7372&icon_color=6cffd0&text_color=dbdbdb&bg_color=252334&hide_border=TRUE
> Add new theme

- themes/index.js
> Added panda theme

- docs/readme_es.md
Match the link of Top Languages Card with the title of his section ("Tarjeta de Lenguajes Principales").
This is for HacktoberFest (hacktoberfest-approved).
> Match link with section title

- themes/index.js
screenshot:
vscode theme link:
https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2
> Added theme cobalt2

- themes/index.js
> Noctis minimus

- themes/index.js
Adding Apple Swift Language as a new theme
> Adding swift language theme

- package.json
- scripts/preview-theme.js
Improved theme preview script with 
- better parsing of diffs & broken json
- automated color contrast checks
- automated warnings
see #1436
> feat: improved theme preview script

- package.json
https://github.com/axios/axios/pull/3410
> axios from 0.19.2 to 0.24.0 

- themes/index.js
Added Apprentice theme.
Preview:
> Add Apprentice theme

- src/fetchers/repo-fetcher.js
- src/fetchers/stats-fetcher.js
- src/fetchers/top-languages-fetcher.js
https://docs.github.com/en/rest/overview/other-authentication-methods
> fix: auth token header

- src/common/languageColors.json
Refer: https://github.com/github/linguist/commit/1ad2f29e5486075c31e68686cdf69cc0e09075b2#diff-9c337ec09ccaaa1374713aad9ba26cdc1308586a27cb309a883a0b19bde663d8
> update Kotlin color

- readme.md
Fixed grammatical error in readme.md
> fixed grammatical error in readme.md

- src/translations.js
Replacement of #1240 which seems to be broken.
> add uzbek translation

- readme.md
some minor spelling and grammatical fixes for the first part of the README to help with project performance
> spelling & grammar in README

- docs/readme_de.md
There were some spelling issues, but probably it's all right as it was last version, what do you think?
> Updated readme_de.md

- docs/readme_pt-BR.md
This link don't work, because the pt-BR not is demo but is 'demonstração'
> Update link view demo in pt-BR

- CONTRIBUTING.md
I forked the project and tried running it, but got an error saying 
The value for maxDuration must be between 1 second and 10 seconds, in order to increase this limit upgrade your plan: https://vercel.com/pricing
- We have to set the maxDuration to 10 for free plans in vercel.json
> Update docs to mention maxDuration to 10

- src/translations.js
I've added translations for swedish speakers.
languate tag: se
> added swedish translations

- api/index.js
- api/pin.js
- api/top-langs.js
- api/wakatime.js
- tests/api.test.js
A temporary solution for PATs exhaustion.
> fix: temporarily increase the cache hours

- src/cards/stats-card.js
- src/common/Card.js
- tests/__snapshots__/renderWakatimeCard.test.js.snap
- Makes the svg accessible to screen readers
> feat: added accessibility label and title in svg

- docs/readme_pt-BR.md
> correcting a word on readme pt-br

- .github/workflows/test.yml
Reverts anuraghazra/github-readme-stats#1849
> Revert "fix: prevent npm dependency error"

- scripts/preview-theme.js
does not passes -> does not pass
> Fixed a small grammatical mistake / typo

- readme.md
https://github.com/anuraghazra/github-readme-stats/issues/1888#issuecomment-1196263440
> Note for temporary cache inc

- src/calculateRank.js
Issue#
------
`No-Story`
Description:
------
Refactored level calculation Method
> Refactor level calculator

- tests/card.test.js
> fix: test passes with more specific querySelector

- .github/workflows/top-issues-dashboard.yml
Fixes top-issues-action recipe syntax.
> ci: fix top-issues-action syntax

- readme.md
> Remove unneeded underscore from Readme

- readme.md
Added default values to theme card parameters in the Readme file.
Add option defaults to README. #2030
> feat: added default options to readme

- readme.md
Replaced .svg that has a dead img url with a JPEG from the official give India website.
> Fix Give India Logo in readme.md

- readme.md
- src/cards/repo-card.js
- src/cards/top-languages-card.js
Updated the default values. I wasn't really sure about the `hide_progress` default value in the Wakatime Card Exclusive Options.
> update default values in readme

- readme.md
A PR with respect to a failed PR #2091 
Closes #2030 
Modified : readme.md
Added default values to few card
> feat: default values for wakatime and language

- readme.md
This PR fixes some small grammar errors in the README.
> docs: improve readme syntax

- readme.md
Updated Readme.md - The guide on deploying your own Vercel instance
> Update the Vercel deployement guide

- src/common/createProgressNode.ts
* Add createProgressNode type
@rickstaa
> Add createProgressNode type

- readme.md
> docs: fix readme logo alignment

- src/calculateRank.js
- src/cards/repo-card.js
- src/cards/stats-card.js
- src/cards/top-languages-card.js
- src/cards/wakatime-card.js
- src/common/Card.js
- src/common/I18n.js
- src/common/createProgressNode.js
- src/common/utils.js
- src/fetchers/repo-fetcher.js
- src/fetchers/stats-fetcher.js
- src/fetchers/top-languages-fetcher.js
- src/fetchers/wakatime-fetcher.js
- src/getStyles.js
- src/translations.js
This PR resolves https://github.com/anuraghazra/github-readme-stats/issues/2032
> fix: adding doc strings to files in src folder where it was missing

- scripts/close-stale-theme-prs.js
- scripts/helpers.js
- scripts/preview-theme.js
This commit makes sure the PR staleness is checked by the latest review that is done.
> ci: fix stale closer action review sort bug

- .github/workflows/stale-theme-pr-closer.yaml
- scripts/close-stale-theme-prs.js
- scripts/preview-theme.js
This commits increases the theme invalid close time to 20 days.
> ci: increase invalid theme close time

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR makes sure that users can not submit empty issue templates.
> refactor: make issue templates required

- docs/readme_pt-BR.md
I noticed some minor issues with the Brazilian readme version. Then I made this PR to update it. It going to help my hacktoberfest \o/
> Update brazilian readme

- themes/index.js
Hi Anurag or whoever is reading this,
I have a new theme that I would like to contribute to the GitHub README Stats repository, I hope you enjoy!
Bradley
> Added Date Night theme to index.js

- package-lock.json
Reverts anuraghazra/github-readme-stats#2373
> Revert "build(deps): bump json5 from 2.2.1 to 2.2.3"

- scripts/push-theme-readme.sh
Reverts anuraghazra/github-readme-stats#2271
> Revert "ci: fix theme readme generation action"

- api/top-langs.js
- readme.md
- src/cards/top-languages-card.js
- src/cards/types.d.ts
- src/common/createProgressNode.js
Reverts anuraghazra/github-readme-stats#2197.
@RedHeadphone, I sadly have to revert this PR to check if I can get the project to work again. I don't think it was your pull request, but I just want to be sure. You can reopen this PR, and I will merge it again after we fix the public Vercel instance.
> Revert "Add loading Animation to Most used Language card"

- src/common/retryer.js
> fix: retryer fixed

- scripts/push-theme-readme.sh
Reverts anuraghazra/github-readme-stats#2394
> Revert "Revert "ci: fix theme readme generation action""

- themes/index.js
This colors were taken from One Dark Pro theme in VSCode extention. Please add it and I will use it in my profile
> Add one_dark_pro

- themes/index.js
This fixes a JSON bug that was introduced in https://github.com/anuraghazra/github-readme-stats/pull/2507.
> fix: fix JSON themes bug.

- express.js
- readme.md
Added an easy way to deploy using services other than Vercel
- Added an `express.js` file
- Updated documentation
> Add option to deploy using other services

- express.js
> refactor: format code

- scripts/preview-theme.js
Preview theme workflow fails. Hopefully fixes it.
> Preview theme workflow fix

- scripts/preview-theme.js
@Zo-Bro-23 This should fix the issues you are having. I, unfortunately, don't have time to debug it, but you can debug the script locally by setting the `MOCK_PR_NUMBER` and `GITHUB_TOKEN` environmental variables.
> ci: fix theme preview action

- scripts/push-theme-readme.sh
Second attempt to safe the `unsafe directory` bug.
> ci: fix theme docs generate bug

- CONTRIBUTING.md
This pull requests improves the CONTRIBUTION.md so that developers have an easier time contributing.
> feat: improve CONTRIBUTING.md

- readme.md
> docs: update give logo

- readme.md
Fixed the location of the language algorithm explanation.
> docs: fix README language card usage order

- .github/workflows/prs-cache-clean.yml
This workflow will delete all caches related to PR when it was merged or closed.
> Add PRs cache cleaning workflow

- tests/renderWakatimeCard.test.js
> Cover with test changes in #2662 pull request

- tests/e2e/e2e.test.js
Makes sure the e2e test works with #1186.
> fix e2e rank

- api/top-langs.js
- src/cards/top-languages-card.js
This is my solution for #2737 alternate to #2746.
> Fixed layout toLowerCase bug

- readme.md
> Add note about private contributions into readme

- readme.md
> docs: improve readme links

- CONTRIBUTING.md
This pull request adds the steps that can be used to debug the code to the CONTRIBUTION.md file.
> docs: add package debug steps to contribution guidelines

- themes/index.js
Added neon themes with bright colors that goes well with dark backgrounds.
> Added neon theme

- tests/e2e/e2e.test.js
This PR ensures the new rank values introduced by #2762 are added to the 2e2 test.
> test: update 2e2 rank values

- .github/workflows/e2e-test.yml
- .github/workflows/generate-theme-doc.yml
- .github/workflows/preview-theme.yml
- .github/workflows/stale-theme-pr-closer.yaml
- .github/workflows/test.yml
- .github/workflows/update-langs.yaml
> Use node 18.x in continuous integration

- src/cards/wakatime-card.js
Related to #2818 
This one can be merged after #2819 and node version update on production (#2823).
> Use default json import

- src/translations.js
@qwerty541 here are the translations we forgot in #1404.
> refactor: add PR review translations

- src/cards/wakatime-card.js
Reverts anuraghazra/github-readme-stats#2820
> Revert "Use default json import"

- src/cards/top-languages-card.js
> Top langs card: Increase maximum languages count to 20

- readme.md
> Docs: Increase maximum languages count to 20

- src/common/I18n.js
Related to #2850. I think the translation error could be improved.
> feat: improve locale translation not found error

- docs/readme_de.md
- docs/readme_es.md
- docs/readme_kr.md
- docs/readme_nl.md
- docs/readme_np.md
- docs/readme_pt-BR.md
- docs/readme_tr.md
- readme.md
Wakatime card examples inside readme currently showing "Profile is not public" error. I choosed another active user from wakatime leaderboard.
> Docs: change example wakatime profile

- readme.md
We forgot to remove the progress rank icon example 🤔.
> remove progress icon example

- src/calculateRank.js
For your consideration, a [shorthand property in object initialisation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#property_definitions).
> refactor: object shorthand

- .github/workflows/ossf-analysis.yml
- readme.md
> CI: Add OSSF scorecard analysis workflow

- readme.md
Thanks again for your effort anuraghazra!
> Fixed typos and grammars in readme.md

- .github/workflows/test.yml
Trying to avoid test workflow duplicate
> CI: Avoid test workflow duplicate

- package.json
Fixed problem described in https://github.com/anuraghazra/github-readme-stats/pull/2928#issuecomment-1631178683. Should be merged after #2930 and #2931
> Fix lint command

- src/translations.js
> Uppercase total reviews title to match all another titles style

- .github/workflows/deploy-prep.yml
- .github/workflows/e2e-test.yml
- .github/workflows/empty-issues-closer.yaml
- .github/workflows/generate-theme-doc.yml
- .github/workflows/label-pr.yml
- .github/workflows/preview-theme.yml
- .github/workflows/prs-cache-clean.yml
- .github/workflows/stale-theme-pr-closer.yaml
- .github/workflows/test.yml
- .github/workflows/top-issues-dashboard.yml
- .github/workflows/update-langs.yaml
> CI: dependencies pinned by hashes

- .vscode/settings.json
- CONTRIBUTING.md
- readme.md
- scripts/preview-theme.js
This pull request ensures that the admonitions are in line with the new GFM specifications (see https://github.com/orgs/community/discussions/16925#discussioncomment-6506860).
> docs: fix broken admonitions

- scripts/preview-theme.js
@rickstaa Please take a proper look, i hope it will fix theme preview workflow, but i have no idea how to test it before merging. 
I have found pull requests with major changes in 5.0.0 version of @actions/github pacakge: https://github.com/actions/toolkit/pull/783/files
> CI: Fix theme preview workflow

- tests/fetchStats.test.js
This pull request covers the following lines with test:
https://app.codecov.io/gh/anuraghazra/github-readme-stats/blob/master/src%2Ffetchers%2Fstats-fetcher.js#L154
> Tests: Stats card: Add invalid username fetcher test

- CONTRIBUTING.md
Related to https://github.com/anuraghazra/github-readme-stats/pull/3060#issuecomment-1695177245
> docs(contributing guide): add community positive feedback requirement for themes PRs

- scripts/preview-theme.js
Related to https://github.com/anuraghazra/github-readme-stats/pull/3060#issuecomment-1695177245
> ci(themes-preview): add themes PRs positive feedback requirement

- tests/card.test.js
This pull request covers the following lines with test:
https://app.codecov.io/gh/anuraghazra/github-readme-stats/blob/master/src%2Fcommon%2FCard.js#L107
> tests: add missing card set title test

- docs/readme_cn.md
As a Simplified Chinese user, if you are unsure, it should have been Traditional Chinese or something else
> fix: Simplified Chinese error

- .eslintrc.json
- src/common/utils.js
- src/fetchers/gist-fetcher.js
https://eslint.org/docs/latest/rules/no-use-before-define
> infra: enable no-use-before-define eslint rule

- src/common/utils.js
This pull request conflicts with https://github.com/anuraghazra/github-readme-stats/pull/3273, if current will be merged earlier, it should be merged with master branch first and vice versa.
> refactor: fix typo in TRY_AGAIN_LATER constant name

- scripts/generate-theme-doc.js
Reverts anuraghazra/github-readme-stats#3308
> Revert "Update generate-theme-doc.js"

- .eslintrc.json
- src/common/utils.js
https://eslint.org/docs/latest/rules/radix
> infra: enable radix eslint rule

- CONTRIBUTING.md
@rickstaa We still receive a lot of themes PRs, so i want to improve visability of this policy.
It was already warning inside our automatic themes PRs reviews workflow message.
https://github.com/anuraghazra/github-readme-stats/blob/master/scripts/preview-theme.js#L32-L33
> docs(contributions): improve visability of themes merging policy

- CONTRIBUTING.md
Related to https://github.com/anuraghazra/github-readme-stats/pull/3138#pullrequestreview-1685768973
> docs(contributions): add one theme per pull request rule

- scripts/preview-theme.js
Related to https://github.com/anuraghazra/github-readme-stats/pull/3138#pullrequestreview-1685768973
> ci(theme preview): add one theme per pull request rule

- readme.md
Related to https://github.com/anuraghazra/github-readme-stats/issues/3404#issue-1955989337
> docs: themes addition paused

- CONTRIBUTING.md
Related to https://github.com/anuraghazra/github-readme-stats/issues/3404#issue-1955989337
> docs(contributing): themes addition paused

- .github/workflows/top-issues-dashboard.yml
Related to https://github.com/anuraghazra/github-readme-stats/issues/3404#issue-1955989337
> ci(top issues dashboard): themes addition paused

- .eslintrc.json
https://eslint.org/docs/latest/rules/no-class-assign
> infra: enable no-class-assign eslint rule

- .eslintrc.json
https://eslint.org/docs/latest/rules/no-const-assign
> infra: enable no-const-assign eslint rule

- .eslintrc.json
https://eslint.org/docs/latest/rules/no-dupe-class-members
> infra: enable no-dupe-class-members eslint rule

- tests/fetchWakatime.test.js
Same changes as in https://github.com/anuraghazra/github-readme-stats/pull/3411
> tests(wakatime-fetcher): fix brand casing

- .eslintrc.json
https://eslint.org/docs/latest/rules/constructor-super
> infra: enable constructor-super eslint rule

- .eslintrc.json
https://eslint.org/docs/latest/rules/keyword-spacing
> infra: enable keyword-spacing eslint rule and remove decrecated space-*-keyword rules

- .eslintrc.json
https://eslint.org/docs/latest/rules/no-delete-var
> infra: enable no-delete-var eslint rule

- .eslintrc.json
https://eslint.org/docs/latest/rules/no-caller
> infra: enable no-caller eslint rule
